apiVersion: apps/v1
kind: Deployment
metadata:
  name: much-todo-api
  namespace: much-to-do
spec:
  selector:
    matchLabels:
      app: much-todo-api
  template:
    metadata:
      labels:
        app: much-todo-api
    spec:
      containers:
      - name: backend
        image: much-to-do-backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/much_todo_db"
        - name: JWT_SECRET_KEY
          value: "your_secret_key"
---
apiVersion: v1
kind: Service
metadata:
  name: much-todo-api
  namespace: much-to-do
spec:
  type: NodePort
  selector:
    app: much-todo-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
